Update to grainstore 1.8.1
Grainstore 1.8.1 contains a fix that makes mapnik v3.0.12 upgradeable to
v3.0.15 seamlessly.

This fixes this error:
```
  4) multilayer layergroup with 2 layers, each with its style (grid.json, layer 1):
     Error: No CartoCSS transform path from 3.0.12 to 3.0.15
      at StyleTrans.transform (/srv/node_modules/grainstore/lib/grainstore/style_trans.js:90:13)
      at MMLBuilderInline.transformStyle (/srv/node_modules/grainstore/lib/grainstore/mml-builder/mml-builder-inline.js:231:37)
      at MMLBuilderInline.render (/srv/node_modules/grainstore/lib/grainstore/mml-builder/mml-builder-inline.js:167:26)
      at MMLBuilderInline.toXML (/srv/node_modules/grainstore/lib/grainstore/mml-builder/mml-builder-inline.js:157:10)
      at MMLBuilder.toXML (/srv/node_modules/grainstore/lib/grainstore/mml-builder/mml-builder.js:53:49)
      at Function.initBuilder (/srv/lib/windshaft/renderers/mapnik/factory.js:170:67)
...
```